### ISSUE TITLE
Add a pull request template file

### ISSUE THREAD

**Issue by Mihir-Karbelkar** [caffeinaholics/Login#6]
Every project needs a pull request template file and hence we should add a pull request template file in out project. Comment down below to get the discussion flowing.

**Comment by tanishghosh** [comment]
I would like to work on this...

**Comment by Mihir-Karbelkar** [comment]
Great go ahead. You can find pull request templates in many open source projects.

**Comment by tanishghosh** [comment]
this is done, right?

**Comment by Mihir-Karbelkar** [comment]
This is done
